.TH teepeedee "1"

.SH NAME
teepeedee \- personal web (HTTP) and FTP server

.SH SYNOPSIS
.B teepeedee 
[ confdir ]

.SH DESCRIPTION
teepeedee is a personal web (HTTP) and FTP server.  teepeedee can use SSL to
serve HTTPS.

teepeedee can listen on any number of ports and provide entirely different
views of the filesystem to different users.

.SH OPTIONS
.TP
confdir
The directory to read configuration from.  By default this is
/etc/teepeeedee.

See /usr/share/doc/teepeedee/README.gz for the configuration directory
format and /usr/share/doc/teepeedee/examples/configuration-examples for
examples.

.SH AUTHORS
John Fremlin

